D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF01.inp 0 SF01_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF02.inp 0 SF02_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF03.inp 0 SF03_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF04.inp 0 SF04_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF05.inp 0 SF05_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF06.inp 0 SF06_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF07.inp 0 SF07_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF08.inp 0 SF08_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 SF09.inp 0 SF09_out.dat
