D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB11.inp 0 MB11_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB12.inp 0 MB12_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB13.inp 0 MB13_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB14.inp 0 MB14_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB15.inp 0 MB15_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB16.inp 0 MB16_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB17.inp 0 MB17_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB18.inp 0 MB18_out.dat
D:\drm_monolayer\build\release\drm_monolayer_main.exe  1 MB19.inp 0 MB19_out.dat
